'use client'

import { useEffect, useState } from 'react'
import { MediaUploader, type MediaRecord } from '@/components/MediaUploader'
import { createClient } from '@/lib/supabase/browser'

type GalleryImage = MediaRecord & { galleryId: string; title: string; description: string; display_order: number; active: boolean }
export default function FestivalImagesPage({ params }: { params: { id: string } }) {
  const [festival, setFestival] = useState<{ id: string; name: string; slug: string } | null>(null); const [images, setImages] = useState<GalleryImage[]>([]); const [message, setMessage] = useState('')
  useEffect(() => { const load = async () => { const supabase = createClient(); if (!supabase) return; const { data: festivalData } = await supabase.from('festivals').select('id,name,slug').eq('slug', params.id).maybeSingle(); if (!festivalData) return; setFestival(festivalData); const { data } = await supabase.from('festival_images').select('id,title,description,display_order,active,media:media!festival_images_media_id_fkey(*)').eq('festival_id', festivalData.id).order('display_order'); setImages((data ?? []).map((row) => ({ ...(row.media as unknown as MediaRecord), galleryId: row.id, title: row.title, description: row.description, display_order: row.display_order, active: row.active }))) }; load() }, [params.id])
  async function addImage(record: MediaRecord | null) { if (!record || !festival) return; const supabase = createClient(); if (!supabase) return; const { data, error } = await supabase.from('festival_images').insert({ festival_id: festival.id, media_id: record.id, title: record.file_name, display_order: images.length + 1 }).select('id,title,description,display_order,active,media:media!festival_images_media_id_fkey(*)').single(); if (error) return setMessage('Não foi possível salvar a imagem na galeria.'); setImages([...images, { ...(data.media as unknown as MediaRecord), galleryId: data.id, title: data.title, description: data.description, display_order: data.display_order, active: data.active }]); setMessage('Imagem adicionada ✓') }
  async function removeImage(image: GalleryImage) { if (!confirm(`Tem certeza que deseja remover esta imagem da galeria?\n\n${image.file_name}`)) return; const supabase = createClient(); if (!supabase) return; const result = await supabase.from('festival_images').delete().eq('id', image.galleryId); if (result.error) return setMessage('Não foi possível remover a imagem da galeria.'); setImages(images.filter((item) => item.galleryId !== image.galleryId)); setMessage('Imagem removida da galeria ✓') }
  if (!festival) return <div className="admin-empty">Carregando imagens...</div>
  return <div className="admin-narrow"><div className="admin-page-heading compact"><div><p className="admin-eyebrow">{festival.name}</p><h1>Imagens do festival</h1><p>Esta tela gerencia somente a galeria interna. Ela não altera a imagem exibida no card público.</p></div></div>{message && <p className="admin-save-message">{message}</p>}<section className="admin-panel gallery-context-intro"><p className="admin-eyebrow">CAPA DO FESTIVAL</p><h2>A capa é gerenciada na edição do festival.</h2><p>Use a área <strong>Imagem de capa</strong> para definir o arquivo que aparece no card de `/festivais`.</p></section><section><p className="admin-eyebrow">GALERIA DO FESTIVAL</p><h2 className="admin-section-title">Imagens adicionais</h2><div className="festival-gallery-grid">{images.map((image) => <article className="gallery-admin-card" key={image.galleryId}><div className="gallery-admin-image" style={{ backgroundImage: `url(${image.url})` }} /><strong>{image.title}</strong><small>{image.description || 'Sem descrição'} · ordem {image.display_order}</small><button className="admin-outline" onClick={() => removeImage(image)}>Excluir imagem</button></article>)}<MediaUploader label="Adicionar imagem à galeria" context={`festivals/${festival.slug}/gallery`} mediaType="festival" slug={festival.slug} onChange={addImage} /></div></section></div>
}
