'use client'

import { FormEvent, useState } from 'react'
import { createClient } from '@/lib/supabase/browser'

const initial = { title: 'FESTIVAIS', subtitle: 'Três experiências. Um só sabor.', description: 'Escolha seu festival e descubra uma nova forma de viver o sushi.', button: 'VER FESTIVAIS', updatedTitle: 'PREÇOS ATUALIZADOS', updatedDescription: 'Nosso cardápio é digital e pode ser atualizado sempre que necessário.', updatedComplement: 'Consulte sempre a versão mais recente.', company: 'JAPAZ SUSHI', footerPrimary: 'TRADIÇÃO JAPONESA • SABOR EM CADA DETALHE', footerSecondary: 'São Paulo · Brasil', copyright: '© Japaz Sushi' }
export default function LandingAdminPage() {
  const [form, setForm] = useState(initial); const [status, setStatus] = useState('')
  async function save(event: FormEvent) { event.preventDefault(); const supabase = createClient(); if (!supabase) return setStatus('Configure as variáveis do Supabase para salvar.'); const results = await Promise.all([supabase.from('site_settings').upsert({ key: 'landing.hero', value: { title: form.title, subtitle: form.subtitle, description: form.description, button: form.button } }, { onConflict: 'key' }), supabase.from('site_settings').upsert({ key: 'landing.updated', value: { title: form.updatedTitle, description: form.updatedDescription, complement: form.updatedComplement } }, { onConflict: 'key' }), supabase.from('site_settings').upsert({ key: 'footer', value: { company: form.company, primary: form.footerPrimary, secondary: form.footerSecondary, copyright: form.copyright } }, { onConflict: 'key' })]); setStatus(results.some((result) => result.error) ? 'Não foi possível salvar as alterações.' : 'Alterações salvas ✓') }
  const field = (key: keyof typeof form, label: string) => <label>{label}<input value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>
  return <div className="admin-narrow"><div className="admin-page-heading compact"><div><p className="admin-eyebrow">CONTEÚDO PÚBLICO</p><h1>Landing Page</h1><p>Edite a experiência que o cliente vê.</p></div></div>{status && <p className="admin-save-message">{status}</p>}<form className="admin-panel admin-form" onSubmit={save}><div className="panel-heading"><div><p className="admin-eyebrow">HERO</p><h2>Primeiro impacto</h2></div></div><label>Logo / nome<input value="JAPAZ SUSHI" readOnly /></label>{field('title', 'Título principal')}{field('subtitle', 'Subtítulo')}<label>Descrição<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label>{field('button', 'Texto do botão')}<div className="panel-heading section-divider"><div><p className="admin-eyebrow">ATUALIZAÇÃO</p><h2>Aviso de preços</h2></div></div>{field('updatedTitle', 'Título')}{field('updatedDescription', 'Descrição')}{field('updatedComplement', 'Texto complementar')}<div className="panel-heading section-divider"><div><p className="admin-eyebrow">FOOTER</p><h2>Rodapé institucional</h2></div></div>{field('company', 'Nome da empresa')}{field('footerPrimary', 'Texto principal')}{field('footerSecondary', 'Texto secundário')}{field('copyright', 'Direitos autorais')}<p className="admin-field-note">Imagens, Instagram, WhatsApp, endereço e horário usam o mesmo registro `site_settings` e podem ser conectados ao editor de mídia.</p><button className="admin-primary">SALVAR ALTERAÇÕES</button></form></div>
}
