'use client'

import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { Plus, Pencil, Eye, Trash2 } from 'lucide-react'
import { createClient } from '@/lib/supabase/browser'

type FestivalRow = { id: string; name: string; slug: string; description: string; price: number; active: boolean; display_order: number; image_url: string | null; festival_categories?: { festival_items?: unknown[] }[] }
export function AdminFestivalsClient({ initialFestivals }: { initialFestivals: FestivalRow[] }) {
  const [festivals, setFestivals] = useState(initialFestivals)
  const [editing, setEditing] = useState<FestivalRow | null>(null)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const [form, setForm] = useState({ name: '', slug: '', description: '', price: '0', active: true, display_order: '1' })
  function startEdit(festival: FestivalRow) { setEditing(festival); setForm({ name: festival.name, slug: festival.slug, description: festival.description, price: String(festival.price), active: festival.active, display_order: String(festival.display_order) }) }
  function startNew() { setEditing(null); setForm({ name: '', slug: '', description: '', price: '0', active: true, display_order: String(festivals.length + 1) }) }
  async function save(event: FormEvent) { event.preventDefault(); const supabase = createClient(); if (!supabase) return setMessage('Configure o Supabase para salvar.'); setSaving(true); const payload = { ...form, price: Number(form.price), display_order: Number(form.display_order) }; const result = editing ? await supabase.from('festivals').update(payload).eq('id', editing.id).select().single() : await supabase.from('festivals').insert(payload).select().single(); if (result.error) setMessage(result.error.message); else { setMessage('Alterações salvas ✓'); setFestivals(editing ? festivals.map((item) => item.id === editing.id ? { ...item, ...result.data } : item) : [...festivals, result.data]); setEditing(null) } setSaving(false) }
  async function remove(id: string) { if (!confirm('Tem certeza que deseja remover este festival?')) return; const supabase = createClient(); if (!supabase) return; await supabase.from('festivals').delete().eq('id', id); setFestivals(festivals.filter((festival) => festival.id !== id)) }
  return <div className="admin-crud-layout"><section><div className="admin-page-heading compact"><div><p className="admin-eyebrow">CATÁLOGO</p><h1>Festivais</h1><p>Controle preços, status e conteúdo do menu.</p></div><button className="admin-primary small" onClick={startNew}><Plus size={16} /> Novo festival</button></div>{message && <p className="admin-save-message">{message}</p>}<div className="admin-festival-list">{festivals.map((festival) => <article className="admin-festival-row" key={festival.id}><div className="admin-festival-thumb" style={{ backgroundImage: `url(${festival.image_url || ''})` }}><span>{festival.active ? 'ATIVO' : 'INATIVO'}</span></div><div className="admin-festival-info"><h2>{festival.name}</h2><p>{festival.description}</p><strong>R$ {Number(festival.price).toFixed(2).replace('.', ',')}</strong><small>{festival.festival_categories?.length ?? 0} categorias · {(festival.festival_categories ?? []).reduce((n, category) => n + (category.festival_items?.length ?? 0), 0)} itens</small></div><div className="admin-row-actions"><button onClick={() => startEdit(festival)} title="Editar"><Pencil size={16} /></button><Link href={`/admin/festivais/${festival.id}/itens`} title="Itens"><span>Itens</span></Link><Link href={`/festivais#festivais`} target="_blank" title="Visualizar"><Eye size={16} /></Link><button onClick={() => remove(festival.id)} title="Excluir"><Trash2 size={16} /></button></div></article>)}</div></section>{(editing || form.name !== '') && <form className="admin-panel admin-form" onSubmit={save}><div className="panel-heading"><div><p className="admin-eyebrow">{editing ? 'EDITAR' : 'NOVO'}</p><h2>Festival</h2></div><button type="button" className="admin-close" onClick={() => { setEditing(null); setForm({ name: '', slug: '', description: '', price: '0', active: true, display_order: '1' }) }}>×</button></div><label>Nome<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Slug<input value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} required /></label><label>Descrição<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="form-two"><label>Preço<input type="number" step="0.01" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} /></label><label>Ordem<input type="number" value={form.display_order} onChange={(e) => setForm({ ...form, display_order: e.target.value })} /></label></div><label className="switch-row">Ativo <input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} /></label><button className="admin-primary" disabled={saving}>{saving ? 'SALVANDO...' : 'SALVAR ALTERAÇÕES'}</button></form>}</div>
}
